name: ci
on:
  pull_request:
  push:
    branches:
      - 'master'
jobs:
  test:
    name: Aircall Test Pager (Node ${{ matrix.node-version }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies with npm
        run: npm install
      - name: Build js files to dist folder
        run: npm run build
      - name: Run tests
        run: npm run test
